"""empty message

Revision ID: 28ac415c0687
Revises: 48cf623eb771
Create Date: 2020-01-20 05:38:22.630869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ac415c0687'
down_revision = '48cf623eb771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_code', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'invite_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'invite_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('invite_code', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
