"""add uploader

Revision ID: 386d8d00876e
Revises: bddb1a7aee2c
Create Date: 2020-02-02 04:36:22.658982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386d8d00876e'
down_revision = 'bddb1a7aee2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('uploader', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'users', ['uploader'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'uploader')
    # ### end Alembic commands ###
