"""init

Revision ID: 4519daacc2b5
Revises: 
Create Date: 2020-02-02 00:19:36.546861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4519daacc2b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('twitter_id', sa.Text(), nullable=True),
    sa.Column('twitter_token', sa.Text(), nullable=True),
    sa.Column('twitter_secret', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    op.drop_table('users')
    # ### end Alembic commands ###
