"""empty message

Revision ID: 48cf623eb771
Revises: ba24ef0b067f
Create Date: 2020-01-20 05:30:32.004412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cf623eb771'
down_revision = 'ba24ef0b067f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_code', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'users', 'invite_code', ['invite_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invite_code')
    # ### end Alembic commands ###
