"""invite nullable

Revision ID: 869daccdaa59
Revises: c468adfca26d
Create Date: 2020-02-02 00:23:47.300534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869daccdaa59'
down_revision = 'c468adfca26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
