"""invite not nullable

Revision ID: 920c6a426b85
Revises: 869daccdaa59
Create Date: 2020-02-02 00:26:35.934005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920c6a426b85'
down_revision = '869daccdaa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invite',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
