"""inv column

Revision ID: c468adfca26d
Revises: 4519daacc2b5
Create Date: 2020-02-02 00:19:59.669436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c468adfca26d'
down_revision = '4519daacc2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'users', 'invites', ['invite'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invite')
    # ### end Alembic commands ###
