- hosts: web
  tasks:

    - name: system deps
      apt:
        pkg:
          - rsync
          - python3
          - python3-dev
          - python3-pip
          - build-essential
          - libcapnp-dev
          - nginx
          - certbot
          - python3-certbot-nginx
          - postgresql
          - libpq-dev

    - name: copy app
      synchronize:
        src: ../../
        dest: /var/www/neettv/
        delete: yes
        rsync_opts:
          - "--chown=www-data:www-data"

    - name: python deps
      pip:
        executable: pip3
        requirements: /var/www/neettv/requirements.txt

    - name: migrate db
      command:
        cmd: flask db upgrade
        chdir: /var/www/neettv
      environment:
        FLASK_APP: web.py
        FLASK_SECRET: "{{ lookup('env', 'FLASK_SECRET') }}"
        DB_URI: postgres://postgres:postgres@localhost:5432/neettv

    - name: gunicorn service
      template:
        src: services/gunicorn.service.tmpl
        dest: /etc/systemd/system/gunicorn.service
        mode: '0600'

    - name: mpvsockserver service
      template:
        src: services/mpvsockserver.service.tmpl
        dest: /etc/systemd/system/mpvsockserver.service
        mode: '0600'

    - name: systemd reload
      systemd: daemon_reload=yes

    - name: start postgres
      systemd:
        service: postgresql
        state: started
        enabled: yes

    - name: restart gunicorn
      systemd:
        service: gunicorn
        state: restarted
        enabled: yes

    - name: restart mpvsockserver
      systemd:
        service: gunicorn
        state: restarted
        enabled: yes

    - name: nginx conf
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default
        mode: '0600'

    - name: reload nginx
      systemd:
        service: nginx
        state: reloaded
        enabled: yes
